# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-04-27 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorSay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='说说编号')),
                ('content', models.TextField(verbose_name='说说内容')),
                ('say_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.Author', verbose_name='所属用户')),
            ],
        ),
    ]
