# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-04-29 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='作者编号')),
                ('username', models.CharField(max_length=50, verbose_name='登录账号')),
                ('userpass', models.CharField(max_length=50, verbose_name='登录密码')),
                ('realname', models.CharField(max_length=50, verbose_name='作者姓名')),
                ('header_img', models.ImageField(default='static/images/headers/default.jpg', upload_to='static/images/headers/')),
                ('age', models.IntegerField(blank=True, default=0, null=True, verbose_name='作者年龄')),
                ('gender', models.CharField(blank=True, max_length=5, null=True, verbose_name='作者性别')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系方式')),
                ('email', models.CharField(blank=True, max_length=20, null=True, verbose_name='电子邮箱')),
                ('join_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='个人介绍')),
            ],
        ),
    ]
