# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-05-01 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键编号')),
                ('content', models.TextField(verbose_name='留言内容')),
                ('msg_time', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
                ('receive_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive', to='author.Author', verbose_name='接收人')),
                ('send_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='author.Author', verbose_name='发表人')),
            ],
        ),
    ]
