# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-05-01 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='相册编号')),
                ('name', models.CharField(max_length=50, verbose_name='相册名称')),
                ('cover', models.ImageField(upload_to='static/images/album/')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='相册描述')),
                ('photo_count', models.IntegerField(default=0, verbose_name='照片数量')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.Author', verbose_name='所属用户')),
            ],
        ),
    ]
