# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-04-20 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='文章编号')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('read_count', models.IntegerField(default=0, verbose_name='阅读次数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论次数')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.Author', verbose_name='作者')),
            ],
        ),
    ]
